#!/usr/bin/env python
from setuptools import setup, find_packages

setup(name='CrossFire Telemetry Mirror',
      version='1.0',
      description='Python processing of Serial Telemetry Data generated by TBS Crossfire protocol',
      author='Patrick Ethier',
      author_email='nuttybrewer@gmail.com',
      url='https://git.com/nuttybrewer/dronetools/',
      packages=find_packages(include=['csrf_serial', 'csrf_serial.*']),
      install_requires=['pyserial', 'binascii'],
      python_requires=">=3.7"
     )